apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kernalpoint-tk-tls
spec:
  secretName: kernalpoint-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kernalpoint.tk
  dnsNames:
    - kernalpoint.tk
    - www.kernalpoint.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kernalpoint.tk
          - www.kernalpoint.tk
